add safe guard and usage when running standalone
git-svn-id: svn+ssh://svn.mageia.org/svn/adm/puppet@1872 db665093-e049-48a9-b3c2-13f1584ce46d

diff --git a/modules/buildsystem/templates/sign-check-package b/modules/buildsystem/templates/sign-check-package
--- a/modules/buildsystem/templates/sign-check-package
+++ b/modules/buildsystem/templates/sign-check-package
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+if [ $# != 3 ] ; then 
+    echo "missing arguments"
+    echo "usage : $0 file key_number key_directory"
+    exit 1
+fi
+ 
 file="$1"
 key="$2"
 keydir="$3"
